TheWaterProject/Models/Cart.cs
namespace TheWaterProject.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public virtual void AddItem(Project proj, int quantity)
        {
            CartLine? line = Lines
                .Where(x => x.Project.ProjectId == proj.ProjectId)
                .FirstOrDefault();

            // Has this item already been added to our cart?
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Project = proj,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Project proj) =>
            Lines.RemoveAll(x => x.Project.ProjectId == proj.ProjectId);

        public virtual void Clear() => Lines.Clear();

        public decimal CalculateTotal() => Lines.Sum(x => 25 * x.Quantity);
        
        public class CartLine
        {
            public int CartLineId { get; set; }
            public Project Project { get; set; }
            public int Quantity { get; set; }
        }
    }
}

TheWaterProject/Models/EFWaterRepository.cs
namespace TheWaterProject.Models
{
    public class EFWaterRepository : IWaterRepository
    {
        private WaterProjectContext _context;
        public EFWaterRepository(WaterProjectContext ctx)
        {
            _context = ctx;
        }
        public IQueryable<Project> Projects => _context.Projects;
    }
}

TheWaterProject/Models/IWaterRepository.cs
namespace TheWaterProject.Models
{
    public interface IWaterRepository
    {
        public IQueryable<Project> Projects { get; }

    }
}

TheWaterProject/Models/Project.cs
using System.ComponentModel.DataAnnotations;

namespace TheWaterProject.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProgramName { get; set; }
        public string ProjectType { get; set; }
        public int ProjectImpact { get; set; }
        public DateTime ProjectInstallation { get; set; }
        public string ProjectPhase { get; set; }
    }
}

TheWaterProject/Models/SessionCart.cs
using System.Text.Json.Serialization;
using TheWaterProject.Infrastructure;

namespace TheWaterProject.Models
{
    public class SessionCart : Cart
    {
        public static Cart GetCart(IServiceProvider services)
        {
            ISession? session = services.GetRequiredService<IHttpContextAccessor>()?
                .HttpContext?.Session;

            SessionCart cart = session?.GetJson<SessionCart>("Cart")
                ?? new SessionCart();

            cart.Session = session;
            return cart;
        }

        [JsonIgnore]
        public ISession? Session { get; set; }

        public override void AddItem(Project proj, int quantity)
        {
            base.AddItem(proj, quantity);
            Session?.SetJson("Cart", this);
        }

        public override void RemoveLine(Project proj)
        {
            base.RemoveLine(proj);
            Session?.SetJson("Cart", this);
        }

        public override void Clear()
        {
            base.Clear();
            Session?.Remove("Cart");
        }
    }
}

TheWaterProject/Models/ViewModels/PaginationInfo.cs
namespace TheWaterProject.Models.ViewModels
{
    public class PaginationInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalNumPages => (int) Math.Ceiling((decimal) TotalItems / ItemsPerPage);
    }
}

TheWaterProject/Models/ViewModels/ProjectsListViewModel.cs
namespace TheWaterProject.Models.ViewModels
{
    public class ProjectsListViewModel
    {
        public IQueryable<Project> Projects { get; set; }
        public PaginationInfo PaginationInfo { get; set; } = new PaginationInfo();

        public string? CurrentProjectType { get; set; }

    }
}

TheWaterProject/Models/WaterProjectContext.cs
using Microsoft.EntityFrameworkCore;

namespace TheWaterProject.Models
{
    public class WaterProjectContext : DbContext
    {
        public WaterProjectContext(DbContextOptions<WaterProjectContext> options): base(options){ }

        public DbSet<Project> Projects { get; set; }
    }
}

TheWaterProject/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TheWaterProject.Models;

namespace TheWaterProject.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

TheWaterProject/Components/ProjectTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TheWaterProject.Models;

namespace TheWaterProject.Components
{
    public class ProjectTypesViewComponent : ViewComponent
    {
        private IWaterRepository _waterRepo;
        public ProjectTypesViewComponent(IWaterRepository temp)
        {
            _waterRepo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedProjectType = RouteData?.Values["projectType"];
            var projectTypes = _waterRepo.Projects
                .Select(x => x.ProjectType)
                .Distinct()
                .OrderBy(x => x);

            return View(projectTypes);
        }
    }
}

TheWaterProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TheWaterProject.Models;
using TheWaterProject.Models.ViewModels;

namespace TheWaterProject.Controllers
{
    public class HomeController : Controller
    {
        private IWaterRepository _repo;
        public HomeController(IWaterRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(string? projectType, int pageNum = 1)
        {
            int pageSize = 5;

            var blah = new ProjectsListViewModel
            {
                Projects = _repo.Projects
                    .Where(x => projectType == null || x.ProjectType == projectType)
                    .OrderBy(x => x.ProjectName)
                    .Skip((pageNum - 1) * pageSize)
                    .Take(pageSize),

                PaginationInfo = new PaginationInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalItems = projectType == null ? _repo.Projects.Count() : _repo.Projects.Where(x => x.ProjectType == projectType).Count()
                },

                CurrentProjectType = projectType

            };
            

            return View(blah);
        }
    }
}

TheWaterProject/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TheWaterProject.Infrastructure;
using TheWaterProject.Models;

namespace TheWaterProject.Pages
{
    public class CartModel : PageModel
    {
        public IWaterRepository _repo;
        public Cart Cart { get; set; }
        public CartModel(IWaterRepository temp, Cart cartService)
        {
            _repo = temp;
            Cart = cartService;
        }

        public string ReturnUrl { get; set; } = "/";
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int projectId, string returnUrl)
        {
            Project proj = _repo.Projects
                .FirstOrDefault(x => x.ProjectId == projectId);

            if (proj != null) 
            {
                Cart.AddItem(proj, 1);
            }

            return RedirectToPage (new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int projectId, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(x => x.Project.ProjectId == projectId).Project);

            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

TheWaterProject/Pages/Cart.cshtml
@page
@model TheWaterProject.Pages.CartModel
@{
}

<h2>Your cart</h2>

<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Project Name</th>
            <th>Quantity</th>
            <th class="text-right">Amount</th>
            <th class="text-right">Subtotal</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var l in Model.Cart?.Lines ?? Enumerable.Empty<Cart.CartLine>())
            {
                <tr>
                    <td class="text-left">@l.Project.ProjectName</td>
                    <td class="text-center">@l.Quantity</td>
                    <td class="text-right">$25</td>
                    <td class="text-right">@((l.Quantity * 25).ToString("c"))</td>
                    <td class="text-center">
                        <form asp-page-handler="Remove" method="post">
                            <input type="hidden" name="projectId" value="@l.Project.ProjectId" />
                            <input type="hidden" name="returnUrl" value="@Model?.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                        </form>
                    </td>
                </tr>
            }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart?.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Donating</a>
</div>

TheWaterProject/Pages/_CartLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>The Water Project</title>
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    </head>

    <body>
        <div class="bg-dark text-white p-2">
        <span class="navbarnavbar-brand m-lg-2">THE WATER PROJECT</span>
        </div>

        <div class="m-1 p-1">
                @RenderBody()
        </div>
    </body>
</html>

TheWaterProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model ProjectsListViewModel

    <h1>The Water Project</h1>

@foreach (Project p in Model.Projects)
    {
        <partial name="ProjectSummary" model="p"/>
        

    }

<div page-model="@Model.PaginationInfo" page-action="Index" page-classes-enabled="true" page-class="btn"
     page-class-normal="btn-outline-dark" page-class-selected="btn-primary" page-url-orojectType="@Model.CurrentProjectType" class="btn-group pull-right m-1"></div>

TheWaterProject/Views/Shared/Components/CartSummary/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Cart

<div class="">
    @if (Model.Lines.Count() > 0)
    {
        <small class="navbar-text">
            <b>Your cart: </b>@Model.Lines.Sum(x => x.Quantity) item(s) 
            @Model.CalculateTotal().ToString("c")
        </small>
    }

    <a class="btn btn-sm btn-secondary navbar-btn" asp-page="/Cart"
        asp-route-returnurl="@ViewContext.HttpContext.Request.PathAndQuery()">
        <i class="fa fa-shopping-cart"></i>
    </a>
</div>

TheWaterProject/Views/Shared/Components/ProjectTypes/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IQueryable<string>

<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index" asp-route-projectType="" asp-route-pageNum="">Home</a>

    @foreach(string pt in Model ?? Enumerable.Empty<string>())
    {
        <a class="btn @(pt ==ViewBag.SelectedProjectType ? "btn-primary" : "btn-outline-secondary")" asp-controller="Home" asp-action="Index" asp-route-projectType="@pt" asp-route-pageNum="1">@pt</a>
    }
</div>

TheWaterProject/Views/Shared/ProjectSummary.cshtml
@using TheWaterProject.Infrastructure
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Project

<div class="card m-1 p-1">
    <h4>
        @Model.ProjectName
        <span class="badge rounded-pill bg-primary text-white float-end"><small>Impact: @Model.ProjectImpact served</small></span>
    </h4>
    <ul>
        <li>Project Type: @Model.ProjectType</li>
        <li>Regional Program: @Model.ProgramName</li>
        <li>Installation Date: @Model.ProjectInstallation</li>
        <li>Project Status: @Model.ProjectPhase</li>
    </ul>

    <form id=@Model.ProjectId method="post" asp-page="/Cart">
        <input type="hidden" asp-for="ProjectId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <button type="submit" class="btn-outline-success btn-sm float-end">Donate</button>
    </form>
    
</div>

TheWaterProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TheWaterProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheWaterProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">THE WATER PROJECT</div>
                <div class="col-6 navbar-text text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:project-types />
        </div>
        <div class="container col-9">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>